[project]
name = "badges-sdk"
version = "0.0.0"
description = "Библиотека, позволяющая другим плагинам добавлять неограниченное количество бейджей пользователям.\n\nНе нарушает правила exteraGram, так так не вмешивается в работу существующих бейджей, а добавляет свою реализацию, не конфликтующую с бейджами самого exteraGram."
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.14"
dependencies = [
    "exteragram-utils>=0.1.3",
]

[dependency-groups]
dev = [
    "ruff>=0.15.4",
    "ty>=0.0.15",
]

[tool.ty.environment]
extra-paths = ["stubs"]
