[versions]
aliuhook = "1.1.3"
desugar_jdk_libs = "2.1.5"
kotlinxCoroutinesCore = "1.11.0"
agp = "9.4.1"
exteraPlugin = "0.1.1"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.11.0" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "26.1.0" }
aliuhook = { module = "com.aliucord:Aliuhook", version.ref = "aliuhook" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
exterastuff-plugin = { id = "io.github.exterastuff.plugin", version.ref = "exteraPlugin" }
