package ru.n08i40k.badges.api

interface BadgesSdk {
    fun getVersion(): String

    fun addBadgeFactory(pluginId: String, factory: ViewFactory)
    fun removeBadgeFactory(factory: ViewFactory)

    // re-call ViewFactory.bind function on every emoji that shows emoji generated by this factory
    fun scheduleRebind(factory: ViewFactory)

    // re-call ViewFactory.bind function on emoji that shows emoji generated by this factory with filter by user id
    fun scheduleRebind(factory: ViewFactory, userId: Long)
}