#!/usr/bin/env python3
"""Ожидает изменения файлов badges-sdk-dev.py, badges_sdk.py и classes.dex,
после чего отправляет собранный badges-sdk-dev.plugin на устройство

Использование: dev_watch.py <source.py> <classes.dex> [--loader loader.py]
               [--debug] [--poll SECONDS]
"""

# generated by claude

import argparse
import logging
import os
import sys
import tempfile
import time

from exteragram_utils.dev_client import (
    AdbManager,
    DeviceConnection,
    parse_metadata,
)

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from embed_dex import embed_loader, embed_source  # noqa: E402

# Из-за большого размера файла, сервер может не успеть обработать такую нагрузку за одну секунду
SOCKET_TIMEOUT = 30.0


def _mtime(path: str) -> float | None:
    try:
        return os.path.getmtime(path)
    except OSError:
        return None


def _build_temp(
    source_path: str,
    dex_path: str,
    temp_path: str,
    loader_path: str | None,
) -> str | None:
    """Возвращает файл плагина с встроенными в него ресурсами"""

    logger = logging.getLogger("watch")

    try:
        with open(source_path, "r", encoding="utf-8") as f:
            source = f.read()
        with open(dex_path, "rb") as f:
            dex = f.read()
        if loader_path is not None:
            with open(loader_path, "r", encoding="utf-8") as f:
                source = embed_loader(source, f.read())
        content = embed_source(source, dex)
    except (OSError, ValueError) as e:
        logger.error(f"Failed to embed '{dex_path}' into '{source_path}': {e}")
        return None

    with open(temp_path, "w", encoding="utf-8") as f:
        f.write(content)

    logger.info(f"Embedded {len(dex) / 1024} kbytes of dex into {temp_path}")
    return content


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)

    # fmt: off
    parser.add_argument("source",                           help="Plugin Python source file")
    parser.add_argument("dex",                              help="Compiled classes.dex to embed")
    parser.add_argument("--loader",                         help="Loader source to inline into the LOADER block")
    parser.add_argument("--debug", action="store_true",     help="Enable device debugger")
    parser.add_argument("--poll", type=float, default=1.0,  help="Poll interval in seconds")
    parser.add_argument("--log-level", choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"], default="INFO")
    # fmt: on

    return parser.parse_args()


def main() -> int:
    args = parse_arguments()

    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    )

    logger = logging.getLogger("watch")

    if not os.path.isfile(args.source):
        logger.error(f"Source file '{args.source}' not found")
        return 1

    with open(args.source, "r", encoding="utf-8") as f:
        metadata = parse_metadata(f.read())

    if metadata is None or not metadata.id:
        logger.error(f"'{args.source}' has no valid plugin metadata (__id__)")
        return 1

    plugin_id = metadata.id

    adb = AdbManager()

    if not adb.setup_device(args.debug):
        logger.error("Failed to set up adb connection")
        return 1

    connection = DeviceConnection(
        debug_enabled=args.debug, response_timeout=int(SOCKET_TIMEOUT)
    )

    if not connection.connect():
        logger.error("Failed to connect to the device")
        return 1

    temp_dir = tempfile.mkdtemp(prefix=f"{plugin_id}-")
    temp_path = os.path.join(temp_dir, os.path.basename(args.source))

    watched = [args.source] + ([args.loader] if args.loader else [])

    logger.info(
        f"Watching {', '.join(repr(path) for path in watched)} and '{args.dex}' "
        f"for plugin '{plugin_id}'"
    )

    # при запуске принудительно загружаем билд
    last_sources = last_dex = object()

    try:
        while True:
            source_mtimes = tuple(_mtime(path) for path in watched)
            dex_mtime = _mtime(args.dex)

            if dex_mtime is None:
                if last_dex is not None:
                    logger.warning(f"Waiting for dex '{args.dex}' to appear...")
                    last_dex = None
                time.sleep(args.poll)
                continue

            if (source_mtimes, dex_mtime) == (last_sources, last_dex):
                time.sleep(args.poll)
                continue

            last_sources, last_dex = source_mtimes, dex_mtime

            content = _build_temp(args.source, args.dex, temp_path, args.loader)
            if content is None:
                time.sleep(args.poll)
                continue

            if connection.write_plugin(plugin_id, content):
                time.sleep(0.3)
                if connection.reload_plugin(plugin_id):
                    logger.info(f"Reloaded plugin '{plugin_id}' on device")
                else:
                    logger.warning(f"Failed to reload plugin '{plugin_id}'")
            else:
                logger.warning(f"Failed to upload plugin '{plugin_id}'")

            time.sleep(args.poll)

    except KeyboardInterrupt:
        logger.info("Stopped by user")

    finally:
        connection.stop_debugger()
        connection.disconnect()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
