#!/usr/bin/env python3
"""Собирает распространяемый лоадер: вставляет исходник лоадера и/или DEX
в виде комментария с кодировкой base64 и сжатием LZMA.

Использование: embed_dex.py <classes.dex> <source.py> [output.py]
               embed_dex.py --loader <loader.py> <classes.dex> <source.py> [output.py]

Если output.py не указан, скрипт перезаписывает source.py.
``--loader`` сперва заменяет LOADER-блок исходника файлом лоадера, и только
потом встраивает DEX.
"""

# generated by claude

import base64
import lzma
import sys

DEX_BEGIN = "# === BADGES SDK DEX BEGIN ==="
DEX_END = "# === BADGES SDK DEX END ==="

LOADER_BEGIN = "# === BADGES SDK LOADER BEGIN ==="
LOADER_END = "# === BADGES SDK LOADER END ==="

# символов на строку (немного, чтобы исходник оставался diff-friendly)
LINE_WIDTH = 120

LZMA_PRESET = 9 | lzma.PRESET_EXTREME


def compress(data: bytes) -> bytes:
    return lzma.compress(data, format=lzma.FORMAT_XZ, preset=LZMA_PRESET)


def _block_bounds(lines: list[str], begin: str, end: str) -> tuple[int, int]:
    """Возвращает индексы строк-маркеров ``begin`` и ``end``."""

    try:
        begin_idx = next(i for i, line in enumerate(lines) if line.strip() == begin)
    except StopIteration:
        raise ValueError(f"marker not found in source: {begin}") from None

    try:
        end_idx = next(
            i for i, line in enumerate(lines) if i > begin_idx and line.strip() == end
        )
    except StopIteration:
        raise ValueError(f"marker not found in source: {end}") from None

    return begin_idx, end_idx


def embed_source(source: str, dex: bytes) -> str:
    """Возвращает исходник с упакованным DEX между DEX-маркерами."""

    lines = source.splitlines()
    begin_idx, end_idx = _block_bounds(lines, DEX_BEGIN, DEX_END)

    encoded = base64.b64encode(compress(dex)).decode("ascii")
    payload = [
        f"# {encoded[i : i + LINE_WIDTH]}" for i in range(0, len(encoded), LINE_WIDTH)
    ]

    new_lines = lines[: begin_idx + 1] + payload + lines[end_idx:]
    return "\n".join(new_lines) + "\n"


def embed_loader(source: str, loader: str) -> str:
    """Возвращает исходник, в котором LOADER-блок заменён файлом лоадера.

    Файл лоадера несёт маркеры в себе, поэтому блок заменяется целиком —
    вместе с маркерами.
    """

    lines = source.splitlines()
    begin_idx, end_idx = _block_bounds(lines, LOADER_BEGIN, LOADER_END)

    # маркеры в лоадере обязательны: без них блок потом не пересобрать
    _block_bounds(loader.splitlines(), LOADER_BEGIN, LOADER_END)

    new_lines = lines[:begin_idx] + loader.splitlines() + lines[end_idx + 1 :]
    return "\n".join(new_lines) + "\n"


def main() -> int:
    argv = sys.argv[1:]

    loader_path = None
    if len(argv) >= 2 and argv[0] == "--loader":
        loader_path = argv[1]
        argv = argv[2:]

    if len(argv) not in (2, 3):
        print(
            f"usage: {sys.argv[0]} [--loader loader.py] <classes.dex> <source.py> "
            "[output.py]",
            file=sys.stderr,
        )
        return 2

    dex_path, source_path = argv[0], argv[1]
    output_path = argv[2] if len(argv) == 3 else source_path

    with open(dex_path, "rb") as f:
        dex = f.read()

    with open(source_path, "r", encoding="utf-8") as f:
        source = f.read()

    try:
        if loader_path is not None:
            with open(loader_path, "r", encoding="utf-8") as f:
                source = embed_loader(source, f.read())

        embedded = embed_source(source, dex)
    except ValueError as e:
        print(f"error: {e} ({source_path})", file=sys.stderr)
        return 1

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(embedded)

    print(f"embedded {len(dex) / 1024} kbytes of DEX into {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
