#!/usr/bin/env python3
"""Embed a classes.dex into the plugin .py as a hex comment block.

The plugin loads its engine by reading its own source and decoding the hex
payload placed between the marker comments (see JvmPluginBridge in the plugin).
Storing the DEX as a comment (not a string literal) keeps its bytes out of the
interpreter heap: comments are dropped by the tokenizer and never become a live
Python object.

Usage: embed_dex.py <path/to/classes.dex> <path/to/source.py> [path/to/output.py]
           [--build-type debug|release]

Without an output path the source is rewritten in place. The build type is
stamped into the ``BUILD_TYPE`` constant of the plugin source: release builds
graft the dex into the host class loader and never eject. The reusable
``embed_source`` helper is what the dev watcher uses to build the temp file it
hands to extera.
"""

# generated by claude

import re
import sys

BEGIN = "# === EMDEDDED DEX BEGIN ==="
END = "# === EMDEDDED DEX END ==="
# hex chars per line (kept modest so the source stays diff-friendly)
LINE_WIDTH = 120

BUILD_TYPES = ("debug", "release")
BUILD_TYPE_RE = re.compile(r'^BUILD_TYPE = ".*"$', re.MULTILINE)


def embed_source(source: str, dex: bytes, build_type: str = "release") -> str:
    """Return ``source`` with ``dex`` hex-encoded between the marker comments.

    ``build_type`` is stamped into the ``BUILD_TYPE`` constant of the source.
    """
    if build_type not in BUILD_TYPES:
        raise ValueError(f"unknown build type: {build_type}")

    source, stamped = BUILD_TYPE_RE.subn(f'BUILD_TYPE = "{build_type}"', source, count=1)
    if stamped != 1:
        raise ValueError("BUILD_TYPE constant not found in source")

    lines = source.splitlines()

    try:
        begin_idx = next(i for i, line in enumerate(lines) if line.strip() == BEGIN)
        end_idx = next(i for i, line in enumerate(lines) if line.strip() == END)
    except StopIteration:
        raise ValueError("DEX markers not found in source") from None

    if end_idx <= begin_idx:
        raise ValueError("END marker precedes BEGIN marker")

    hex_data = dex.hex()
    payload = [
        f"# {hex_data[i : i + LINE_WIDTH]}" for i in range(0, len(hex_data), LINE_WIDTH)
    ]

    new_lines = lines[: begin_idx + 1] + payload + lines[end_idx:]
    return "\n".join(new_lines) + "\n"


def main() -> int:
    argv = sys.argv[1:]
    build_type = "release"

    if "--build-type" in argv:
        index = argv.index("--build-type")
        if index + 1 >= len(argv):
            print("error: --build-type requires a value", file=sys.stderr)
            return 2
        build_type = argv[index + 1]
        del argv[index : index + 2]

    if len(argv) not in (2, 3) or build_type not in BUILD_TYPES:
        print(
            f"usage: {sys.argv[0]} <classes.dex> <source.py> [output.py] "
            f"[--build-type debug|release]",
            file=sys.stderr,
        )
        return 2

    dex_path, source_path = argv[0], argv[1]
    output_path = argv[2] if len(argv) == 3 else source_path

    with open(dex_path, "rb") as f:
        dex = f.read()

    with open(source_path, "r", encoding="utf-8") as f:
        source = f.read()

    try:
        embedded = embed_source(source, dex, build_type)
    except ValueError as e:
        print(f"error: {e} ({source_path})", file=sys.stderr)
        return 1

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(embedded)

    print(f"embedded {len(dex)} bytes of {build_type} DEX into {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
